[package]
name = "star_db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
salsa = { git = "https://github.com/salsa-rs/salsa", package = "salsa-2022", rev = "252d21e358979cd684666ebc32d2bc49d6f1d3f0" }
star_syntax = { path = "../star_syntax" }
